language: minimal

deploy:

  # allow any commit to master to refresh the docs on gh-pages
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # from github, set in TravisCI settings
    local_dir: docs/build/html
    on:
      branch: main
